spring:
  # Config connect DB
  datasource:
    url: 'jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  # Config flyway
  flyway:
    locations: classpath:/db/migration
    fail-on-missing-locations: false
    enabled: true
    default-schema: public
    schemas: public
  # Config spring mail
  mail:
    host: smtp.gmail.com
    username: ${MAIL_SUPPORT}
    password: ${MAIL_PASSWORD}
    port: 587
  # Config file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# LocationIQ
locationiq:
  base-url: ${LOCATIONIQ_URL}
  get-location: ${locationiq.base-url}?key=${LOCATIONIQ_KEY}&q={encodedAddress}&format=json

# Geloky
geloky:
  get-location: https://geloky.com/api/geo/geocode?address={encodedAddress}&key=${GELOKY_KEY}&format=geloky

# Config swagger
springdoc:
  api-docs:
    enabled: true
    path: "/manage/api-docs"
  swagger-ui:
    enabled: true
    path: "/manage/api-docs/swagger-ui.html"
  show-actuator: false

# Config firebase
firebase:
  apiKey: ${FIREBASE_API_KEY}
  authDomain: ${FIREBASE_AUTH_DOMAIN}
  projectId: ${FIREBASE_PROJECT_ID}
  storageBucket: ${FIREBASE_STORAGE_BUCKET}
  messagingSenderId: ${FIREBASE_MESSAGING_SENDER_ID}

# Config application
server:
  port: 8080

# Config log root
#logging:
#  level:
#    root: debug

# JWT
jwt:
  secret-key: '${SECRET_KEY}'

security:
  unprotect: >
    /internal/**,
    /manage/**